// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           16
// Async Callback (empty):               1
// Total number of exported functions:  18

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    saving_rs
    (
        init => init
        deposit => deposit
        claimRewards => claim_rewards_endpoint
        getControllerAddress => controller_address
        getHolderAddress => holder_address
        getAssetTokenIdentifier => asset_token_identifier
        getShareTokenIdentifierForPool => lp_token_identifier_for_pool
        getShareTokenIdentifierForFarm => share_token_identifier_for_farm
        getCurrentPositionForFarm => current_position_for_farm
        getPools => pools
        getPoolsTotalWeight => pools_total_weight
        getZapAddress => zap_address
        getZapStartExchangeForToken => zap_start_exchange_for_token
        getWaitingRewards => waiting_rewards
        addPool => add_pool
        removePool => remove_pool
        setZapStartExchangeForToken => set_zap_start_exchange_for_token
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
