[workspace]
members = [
    "platforms/ashswap",
    "platforms/ashswap/meta",
    "controller",
    "controller/meta",
    "vault",
    "vault/meta"
]

exclude = [
    "platforms/ashswap/interaction"
]