// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           12
// Async Callback (empty):               1
// Total number of exported functions:  14

#![no_std]

// Configuration that works with rustc < 1.73.0.
// TODO: Recommended rustc version: 1.73.0 or newer.
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    controller
    (
        init => init
        deposit => deposit
        withdraw => withdraw
        claimRewards => claim_rewards
        claimControllerRewards => claim_controller_rewards
        rebalance => rebalance
        unbond => unbond
        addPlatform => add_platform
        setPlatformDistribution => set_platforms_distribution
        issueAndSetLocalRoles => issue_and_set_local_roles
        setControllerState => set_controller_state
        setFeesDistribution => set_fees_distribution
        setRewardsPerShare => set_rewards_per_share
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
